---
- name: Include role vars
  include_vars: env_vars.yml

- name: Create directory for etcd binaries
  file: 
    path: /opt/etcd/bin
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Download the Tarball into /tmp directory
  get_url:
    url: https://storage.googleapis.com/etcd/v3.3.13/etcd-v3.3.13-linux-amd64.tar.gz
    dest: /tmp/etcd.tar.gz
    mode: 0700

- name: Extract the Tarball into etcd binary folder
  unarchive: 
    src: /tmp/etcd.tar.gz
    dest: /opt/etcd/bin
    mode: 0700
    extra_opts:
          - --strip-components=1
    remote_src: true

- name: Set permissions for etcd 
  file:
    path: /opt/etcd/bin/etcd
    state: file
    mode: 0700

- name: Set permissions for etcdctl
  file:
    path: /opt/etcd/bin/etcdctl
    state: file
    mode: 0700

- name: "Add /opt/etcd/bin/ to the $PATH environment variable"
  become: yes
  lineinfile:
    dest: /etc/environment
    state: present
    backrefs: yes
    regexp: 'PATH=(["]*)((?!.*?).*?)(["]*)$'
    line: 'PATH={{ ansible_env.PATH }}:/opt/etcd/bin'

- name: "Set the ETCDCTL_API environment variable to the latest"
  become: yes
  lineinfile:
    path: /etc/environment
    line: ETCDCTL_API={{ ETCDCTL_API }}
    state: present
    create: True
    insertafter: EOF